#include "calendar/components/calendarstyles.h"

QString CalendarStyles::getCalendarStyle()
{
    return QString(
        "QCalendarWidget {"
        "   background-color: white;"
        "   border: 2px solid %1;"
        "   border-radius: 12px;"
        "   padding: 10px;"
        "}"
        "QCalendarWidget QWidget#qt_calendar_navigationbar {"
        "   background-color: transparent;"
        "   border: none;"
        "   max-height: 0px;"
        "   min-height: 0px;"
        "}"
        "QCalendarWidget QToolButton {"
        "   background-color: transparent;"
        "   border: none;"
        "   color: transparent;"
        "   max-width: 0px;"
        "   min-width: 0px;"
        "   max-height: 0px;"
        "   min-height: 0px;"
        "}"
        "QCalendarWidget QMenu {"
        "   background-color: white;"
        "   border: 1px solid %1;"
        "   border-radius: 6px;"
        "}"
        "QCalendarWidget QSpinBox {"
        "   background-color: transparent;"
        "   border: none;"
        "   color: transparent;"
        "   max-width: 0px;"
        "   min-width: 0px;"
        "}"
        "QCalendarWidget QAbstractItemView {"
        "   background-color: white;"
        "   border: none;"
        "   color: %2;"
        "   selection-background-color: %3;"
        "   alternate-background-color: #FFF8F8;"
        "}"
        "QCalendarWidget QAbstractItemView:enabled {"
        "   font-size: 15px;"
        "}"
        "QCalendarWidget QHeaderView::section {"
        "   background-color: %4;"
        "   color: %5;"
        "   font-weight: bold;"
        "   border: none;"
        "   padding: 6px;"
        "}"
    ).arg(Colors::BORDER_LIGHT, Colors::TEXT_PRIMARY, Colors::SELECTION_BG, Colors::HEADER_BG, Colors::TEXT_SECONDARY);
}

QString CalendarStyles::getDetailsStyle()
{
    return QString(
        "QWidget {"
        "   background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 %1, stop:1 %2);"
        "   border: 2px solid %3;"
        "   border-radius: 12px;"
        "   padding: 20px;"
        "}"
    ).arg(Colors::GRADIENT_START, Colors::GRADIENT_END, Colors::BORDER_LIGHT);
}

QString CalendarStyles::getListStyle()
{
    return QString(
        "QListWidget {"
        "   background-color: transparent;"
        "   border: none;"
        "   padding: 0px;"
        "   color: %1;"
        "}"
        "QListWidget::item {"
        "   border: none;"
        "   border-radius: 4px;"
        "   padding: 4px;"
        "   margin: 0px;"
        "}"
        "QListWidget::item:selected {"
        "   background-color: transparent;"
        "}"
        "QListWidget::item:hover {"
        "   background-color: transparent;"
        "}"
        "QScrollBar:vertical {"
        "   background-color: transparent;"
        "   width: 4px;"
        "   border: none;"
        "   border-radius: 2px;"
        "   margin: 0px;"
        "}"
        "QScrollBar::handle:vertical {"
        "   background-color: #CCCCCC;"
        "   border-radius: 2px;"
        "   min-height: 10px;"
        "   margin: 0px;"
        "}"
        "QScrollBar::handle:vertical:hover {"
        "   background-color: #AAAAAA;"
        "}"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
        "   border: none;"
        "   background: transparent;"
        "   height: 0px;"
        "}"
        "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {"
        "   background: transparent;"
        "}"
    ).arg(Colors::TEXT_PRIMARY);
}

QString CalendarStyles::getMenuStyle()
{
    return QString(
        "QMenu {"
        "   background-color: white;"
        "   border: none;"
        "   border-radius: 8px;"
        "   padding: 4px;"
        "   color: %1;"
        "   font-weight: bold;"
        "}"
        "QMenu::item {"
        "   padding: 8px 12px;"
        "   border-radius: 4px;"
        "   margin: 1px;"
        "}"
        "QMenu::item:selected {"
        "   background-color: %2;"
        "}"
    ).arg(Colors::TEXT_SECONDARY, Colors::SELECTION_BG);
}